# Generated by Django 4.1.7 on 2023-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
