# Generated by Django 4.1.7 on 2023-03-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOpinion',
            new_name='Opinion',
        ),
    ]
