# Generated by Django 4.1.7 on 2023-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
