# Generated by Django 4.1.7 on 2023-03-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_model', '0002_remove_image_id_alter_image_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product_name',
        ),
    ]
